# Main tests
# ==========
# Build the compiler with makefiles and run the testsuite
name: main

# Configure when to run the workflows. Currently only when
# it affects the `flambda2.0` branch (either pushes to the branch, or pull request against it).
on:
  push:
    branches:
      - flambda2.0-stable
  pull_request:
    branches:
      - flambda2.0-stable

jobs:
  # Makefile-based: compile & run the testsuite
  # ===========================================
  build:

    runs-on: ${{ matrix.os }}

    # Build Matrix
    # --------------
    strategy:
      matrix:
        # Operating system to run tests on. TODO: add macos-latest and windows-latest
        # os: [ubuntu-latest, macos-latest, windows-latest]
        os: [ubuntu-latest]

    # Build ENV
    # ---------
    env:
      # Paralellism for builds
      J: "3"
      # disable flambda invariants else everything takes forever to compile
      OCAMLPARAM: "_,flambda-invariants=0"

    # Build/test steps
    # ----------------
    steps:
    # checkout the repo (shallow clone, currently)
    - name: Checkout the repo
      uses: actions/checkout@master
    # Apply ocamltest patch
    - name: Patch the repo
      run: git apply .github/workflows/ocamltest_makefile.patch
    # Install dependencies
    - name: Install dependencies
      run: sudo apt-get install parallel texlive-latex-extra texlive-fonts-recommended
    # Configure the compiler
    - name: configure
      run: ./configure --enable-flambda
    # Debug step
    - name: Debug step
      run: echo "J is $J"
    # Build ocamlc, ocamlopt and just enough to run the testsuite
    - name: Build the compiler
      run: |
        make -j $J world
        make -j $J ocamlopt
        make -j $J runtimeopt
        make -j $J libraryopt
        make -j $J compilerlibs/ocamlcommon.cmxa
        make -j $J -C otherlibs/str allopt
        make -j $J -C otherlibs/unix allopt
        make -j $J -C otherlibs/bigarray allopt
        make -j $J -C otherlibs/systhreads allopt
        make -j $J -C tools caml-tex
        make       -C testsuite tools lib
    # Generate list of tests to run
    - name: Generate test list
      run: grep -v '#' .github/workflows/test-list > .github/workflows/main.list
    # Run some part of the testsuite
    - name: Running the testsuite
      run: cd testsuite && make list-parallel FILE=../.github/workflows/main.list
    # If the testsuite has failed, dump the relavant ocamltest logs
    - name: Ocamltest failing logs
      if: failure()
      run: cd testsuite && make logs


